spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tiendavirtual?serverTimezone=UTC
    username: root
    password: Admin   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.19:8761/eureka  #http://localhost:8761/eureka  192.168.1.19 || 22.22.0.54
    instance:
      prefer-ip-address: true #si no pongo esto error de DNS al ir con http://localhost...., incluso en el postman tambien
server:
  port: 8000 
springdoc:
  packages-to-scan:
  - com.curso.controller
  paths-to-match:
  - /**
